version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1212
      - MYSQL_DATABASE=demo_db
    volumes:
      - mysql_data1:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # 외부에서 DBeaver 등으로 붙고 싶으면 열기
    ports: 
      - "3338:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1212"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  # 외부에서 redis-cli로 테스트할 일이 없으면 포트 매핑 생략
  # ports:
  #   - "6382:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    

  web:
    build: ./web
    ports:
      - "9092:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3338:3306
      - DB_USER=root
      - DB_PASSWORD=1212
      - DB_NAME=demo_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always  



volumes:
  mysql_data1:
  redis_data:


